name: AI & Robotics Daily

on:
  schedule:
    # 每天 01:30 UTC 运行（北京时间 09:30；美西 18:30（夏令时））
    - cron: "30 1 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate daily report
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}   # 可选：用于读取 repo topics
        run: |
          python ai_robotics_daily.py

      - name: Commit & push
        run: |
          if ! git diff --quiet AI_ROBOTICS_DAILY.md; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add AI_ROBOTICS_DAILY.md
            git commit -m "chore: update AI & Robotics daily"
            git push
          else
            echo "No changes."
          fi
